name: test annotations action

on:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Getting code
      uses: actions/checkout@v2

    - name: Set up node
      uses: actions/setup-node@v1

    - name: Install dependencies
      run: npm install -g make git clang-format

    - name: Run formatter and generate annotations
      run: |
		. generate-annotations.sh
